KEYWORDS = \
{
  "Agriculture": [
    "farming",
    "agriculture",
    "farmer",
    "crop",
    "vegetation",
    "livestock",
    "cultivation",
    "dairy",
    "gardening",
    "irrigation",
    "wheat",
    "domestication",
    "wheat",
    "usda",
    "harvest",
    "soil",
    "agricultural",
    "artisanal",
    "factory farm",
    "rural"
  ],
  "Education": [
    "teacher",
    "student",
    "tutor",
    "curriculum",
    "pedagogy",
    "tuition",
    "school",
    "graduate",
    "textbook",
    "education",
    "diploma",
    "instruction",
    "college",
    "classroom",
    "vocational",
    "literacy",
    "k-12"
    "mooc"
  ],
  "Environmental sustainability": [
    "invasive species",
    "electricity",
    "poaching",
    "climate",
    "sustainability",
    "ecosystem",
    "forest",
    "wildlife",
    "pollution",
    "biodiversity",
    "carbon",
    "wildfire",
    "disaster",
    "smart grid",
    "wind farm",
    "flood",
    "renewable",
    "endangered",
    "habitat",
    "atmospheric",
    "bird",
    "hybrid vehicle",
    "hurricane",
    "environmental"
  ],
  "Healthcare": [
    "diagnosis",
    "prevention",
    "healthcare",
    "disability",
    "mental",
    "vaccination",
    "disease",
    "infection",
    "assistive",
    "elderly",
    "medical",
    "clinical",
    "HIV",
    "patient",
    "genetic",
    "community health",
    "public health",
    "clinic",
    "physician",
    "nutrition",
    "outbreak",
    "x-ray",
    "medicare",
    "symptom",
    "epidemic",
    "opiode"
  ],
  "Combating information manipulation": [
    "false news",
    "fake news",
    "polarization",
    "politic",
    "social network",
    "newspaper",
    "journalism",
    "news article",
    "editorial",
    "social media",
    "opinion",
    "television",
    "scandal",
    "election",
    "trustworthy",
    "misleading",
    "verification",
    "vote",
    "influence maximization",
    "tweet",
    "twitter",
    "facebook"
  ],
  "Social care and urban planning": [
   "crisis",
   "equality",
   "social aid",
   "disaster",
   "homeless",
   "refugee"
   "charity",
   "welfare",
   "volunteer",
   "poverty",
   "social worker",
   "socioeconomic",
   "emergency",
   "altruism",
   "cost of living",
   "community",
   "low-income",
   "food security",
   "drug",
   "city",
   "emergency response",
   "home abandonment",
   "hurricane"
  ],
  "Public safety": [
    "security",
    "crime",
    "police",
    "enforcement",
    "safety",
    "vulnerability",
    "attack",
    "fraud",
    "terrorism",
    "alert",
    "arrest",
    "monitoring",
    "violate",
    "protect",
    "illegal",
    "terrorist",
    "patrol",
    "surveillance",
    "adversary",
    "corruption"
  ],
  "Transportation": [
    "transportation",
    "traffic",
    "rideshare",
    "bike",
    "subway",
    "vehicle",
    "transit",
    "carpool",
    "parking",
    "truck",
    "passenger",
    "bus",
    "railroad",
    "highway",
    "commute",
    "travel",
    "navigation",
    "mobility",
    "taxi",
    "delivery",
    "drive",
    "toll",
    "driver",
    "ride-sharing"
  ]
}

DOMAIN_ABBRS = \
{
    "Agriculture" : "AGRI",
    "Education" : "EDU",
    'Environmental sustainability': "ENV",
    'Healthcare' : "HC",
    'Combating information manipulation' : "IV",
    'Social care and urban planning' : "SC",
    'Public safety' : "PS",
    'Transportation' : "TRANS"
}

TECHNIQUES = \
  {
  "Computer vision": [
    "computer vision",
    "facial recognition",
    "object recognition",
    "object detection",
    "satellite image",
    "satellite imagery",
    "satellite images",
    "motion",
    "image",
    "video",
    "gesture"
  ],
  "Robotics": [
    "robotics",
    "robot",
    "motion",
    "path planning",
    "localization",
    "optimal control",
    "state estimation",
    "multi-robot",
    "robust control",
    "adaptive control",
    "task planning",
    "sensor network",
    "sensing"
  ],
  "Planning, routing, and scheduling": [
    "planning",
    "routing",
    "scheduling",
    "probabilistic planning",
    "plan execution",
    "temporal"
  ],
  "Multiagent systems": [
    "teamwork",
    "agent",
    "multiagent (multi-agent)",
    "agent-based",
    "coordination",
    "collaboration",
    "distributed",
    "opponent"
  ],
  "Natural language processing": [
    "nlp",
    "natural language",
    "dialogue",
    "discourse",
    "information extraction",
    "ontology",
    "question answering",
    "semantics",
    "summarization",
    "speech",
    "text classification",
    "machine translation",
    "translation",
    "text processing"
  ],
  "Knowledge representation and reasoning": [
    "knowledge representation",
    "knowledge acquisition",
    "knowledge engineering",
    "ontology",
    "argumentation",
    "automated reasoning",
    "theorem proving",
    "belief change",
    "case-based",
    "knowledge graph",
    "knowledge base",
    "description logics",
    "logic programming",
    "qualitative reasoning"
  ],
  "Human computation and crowd sourcing": [
    "human computation",
    "crowdsourcing",
    "labeler",
    "AMT",
    "mechanic turk",
    "social network",
    "social networks"
  ],
  "Constraint satisfaction and optimization": [
    "constraint satisfaction",
    "constraint optimization",
    "constrained optimization",
    "constrained programming",
    "constraint programming",
    "mathematical program",
    "linear program",
    "distributed optimization",
    "dsp",
    "integer program",
    "non-convex",
    "nonconvex",
    "optimization",
    "satisfiability",
    "search",
    "SAT"
  ],
  "Game playing and interactive entertainment": [
    "game playing",
    "game design",
    "storytelling",
    "creativity",
    "generative art",
    "autonomous characters,",
    "npc",
    "virtual humans"
  ],
  "Game theory and economic paradigms": [
    "auction",
    "market-based systems",
    "game",
    "game theory",
    "game-theoretic",
    "mechanism design",
    "incentive",
    "negotiation",
    "contract-based systems",
    "social choice",
    "equilibrium",
    "equilibria",
    "opponent",
    "imperfect information",
    "stackelberg",
    "nash",
    "incomplete information",
    "strategic interaction",
    "strategic interactions"
  ],
  "Heuristic search and optimization": [
    "heuristic search",
    "distributed search",
    "search",
    "metareasoning",
    "metaheuristics"
  ],
  "Cognitive modeling": [
    "cognitive modeling",
    "adaptive behavior",
    "agent architecture",
    "cognitive architectures",
    "neural spike",
    "symbolic ai",
    "mental imagery"
  ],
  "Cognitive systems": [
    "conceptual inference",
    "conceptual reasoning",
    "cognitive systems",
    "introspection",
    "meta-cognition",
    "memory storage",
    "memory",
    "memory retrieval",
    "social cognition",
    "structural learning",
    "knowledge capture"
  ],
  "Reasoning under uncertainty": [
    "bayesian network",
    "uncertainty",
    "graphical model",
    "decision theory",
    "probabilistic inference",
    "probabilistic model",
    "sequential decision making",
    "sequential decision-making"
    "markov decision process",
    "mdp",
    "pomdp",
    "stochastic optimization"
  ],
  "Human-AI collaboration": [
    "human-agent",
    "human-computer interaction",
    "human-aware planning",
    "behavior prediction",
    "human-in-the-loop",
    "human-robot",
    "human compatible",
    "teamwork",
    "team formation",
    "trustable",
    "explainable",
    "interpretable",
    "fair",
    "fairness",
    "language acquisition",
    "user experience",
    "usable"
  ],
  "Machine learning": [
    "machine learning",
    "bayesian learning",
    "causal learning",
    "classification",
    "clustering",
    "mining",
    "deep learning",
    "dimensionality reduction",
    "feature selection",
    "ensemble",
    "kernel",
    "learning theory",
    "multi-instance",
    "multi-label",
    "multi-view",
    "online learning",
    "graphical model",
    "recommender systems",
    "reinforcement learning",
    "relational learning",
    "semi-supervised",
    "structured prediction",
    "supervised",
    "time-series",
    "data streams",
    "transfer learning",
    "multi-task",
    "unsupervised"
  ]
}

TECHNIQUE_ABBRS = \
{
    'Computer vision' : "CV",
    'Robotics' : "RO",
    'Planning, routing, and scheduling' : "PRS",
    'Multiagent systems' : "MAS",
    'Natural language processing' : "NLP",
    'Knowledge representation and reasoning' : "KRR",
    'Human computation and crowd sourcing' : "HCCS",
    'Constraint satisfaction and optimization' : "CSO",
    'Game playing and interactive entertainment' : "GPIE",
    'Game theory and economic paradigms' : "GTEP",
    'Heuristic search and optimization' : "HSO",
    'Cognitive modeling' : "CMOD",
    'Cognitive systems' : "CSYS",
    'Reasoning under uncertainty' : "RU",
    'Human-AI collaboration' : "HAI",
    'Machine learning' : "ML"
}

domain_abbrevs = list(map(lambda x: DOMAIN_ABBRS[x], KEYWORDS.keys()))
technique_abbrevs = list(map(lambda x: TECHNIQUE_ABBRS[x], TECHNIQUES.keys()))
